// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/orders.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderDispacherStatusRequest struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId             int64    `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DriverLatitude       float64  `protobuf:"fixed64,3,opt,name=driver_latitude,json=driverLatitude,proto3" json:"driver_latitude,omitempty"`
	DriverLongitude      float64  `protobuf:"fixed64,4,opt,name=driver_longitude,json=driverLongitude,proto3" json:"driver_longitude,omitempty"`
	Status               int64    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDispacherStatusRequest) Reset()         { *m = OrderDispacherStatusRequest{} }
func (m *OrderDispacherStatusRequest) String() string { return proto.CompactTextString(m) }
func (*OrderDispacherStatusRequest) ProtoMessage()    {}
func (*OrderDispacherStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35c5e4664fd1dd, []int{0}
}

func (m *OrderDispacherStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDispacherStatusRequest.Unmarshal(m, b)
}
func (m *OrderDispacherStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDispacherStatusRequest.Marshal(b, m, deterministic)
}
func (m *OrderDispacherStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDispacherStatusRequest.Merge(m, src)
}
func (m *OrderDispacherStatusRequest) XXX_Size() int {
	return xxx_messageInfo_OrderDispacherStatusRequest.Size(m)
}
func (m *OrderDispacherStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDispacherStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDispacherStatusRequest proto.InternalMessageInfo

func (m *OrderDispacherStatusRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderDispacherStatusRequest) GetDriverId() int64 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

func (m *OrderDispacherStatusRequest) GetDriverLatitude() float64 {
	if m != nil {
		return m.DriverLatitude
	}
	return 0
}

func (m *OrderDispacherStatusRequest) GetDriverLongitude() float64 {
	if m != nil {
		return m.DriverLongitude
	}
	return 0
}

func (m *OrderDispacherStatusRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GeneraResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneraResponse) Reset()         { *m = GeneraResponse{} }
func (m *GeneraResponse) String() string { return proto.CompactTextString(m) }
func (*GeneraResponse) ProtoMessage()    {}
func (*GeneraResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35c5e4664fd1dd, []int{1}
}

func (m *GeneraResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneraResponse.Unmarshal(m, b)
}
func (m *GeneraResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneraResponse.Marshal(b, m, deterministic)
}
func (m *GeneraResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneraResponse.Merge(m, src)
}
func (m *GeneraResponse) XXX_Size() int {
	return xxx_messageInfo_GeneraResponse.Size(m)
}
func (m *GeneraResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneraResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneraResponse proto.InternalMessageInfo

func (m *GeneraResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetTripByOrderIDRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTripByOrderIDRequest) Reset()         { *m = GetTripByOrderIDRequest{} }
func (m *GetTripByOrderIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetTripByOrderIDRequest) ProtoMessage()    {}
func (*GetTripByOrderIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35c5e4664fd1dd, []int{2}
}

func (m *GetTripByOrderIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTripByOrderIDRequest.Unmarshal(m, b)
}
func (m *GetTripByOrderIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTripByOrderIDRequest.Marshal(b, m, deterministic)
}
func (m *GetTripByOrderIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTripByOrderIDRequest.Merge(m, src)
}
func (m *GetTripByOrderIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetTripByOrderIDRequest.Size(m)
}
func (m *GetTripByOrderIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTripByOrderIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTripByOrderIDRequest proto.InternalMessageInfo

func (m *GetTripByOrderIDRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetTripByOrderIDResponse struct {
	Data                 *OrderTrip `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetTripByOrderIDResponse) Reset()         { *m = GetTripByOrderIDResponse{} }
func (m *GetTripByOrderIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetTripByOrderIDResponse) ProtoMessage()    {}
func (*GetTripByOrderIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35c5e4664fd1dd, []int{3}
}

func (m *GetTripByOrderIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTripByOrderIDResponse.Unmarshal(m, b)
}
func (m *GetTripByOrderIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTripByOrderIDResponse.Marshal(b, m, deterministic)
}
func (m *GetTripByOrderIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTripByOrderIDResponse.Merge(m, src)
}
func (m *GetTripByOrderIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetTripByOrderIDResponse.Size(m)
}
func (m *GetTripByOrderIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTripByOrderIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTripByOrderIDResponse proto.InternalMessageInfo

func (m *GetTripByOrderIDResponse) GetData() *OrderTrip {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetOrderByIDRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderByIDRequest) Reset()         { *m = GetOrderByIDRequest{} }
func (m *GetOrderByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderByIDRequest) ProtoMessage()    {}
func (*GetOrderByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35c5e4664fd1dd, []int{4}
}

func (m *GetOrderByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderByIDRequest.Unmarshal(m, b)
}
func (m *GetOrderByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderByIDRequest.Merge(m, src)
}
func (m *GetOrderByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderByIDRequest.Size(m)
}
func (m *GetOrderByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderByIDRequest proto.InternalMessageInfo

func (m *GetOrderByIDRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetOrderByIDResponse struct {
	Data                 *Order   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderByIDResponse) Reset()         { *m = GetOrderByIDResponse{} }
func (m *GetOrderByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderByIDResponse) ProtoMessage()    {}
func (*GetOrderByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35c5e4664fd1dd, []int{5}
}

func (m *GetOrderByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderByIDResponse.Unmarshal(m, b)
}
func (m *GetOrderByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderByIDResponse.Merge(m, src)
}
func (m *GetOrderByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderByIDResponse.Size(m)
}
func (m *GetOrderByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderByIDResponse proto.InternalMessageInfo

func (m *GetOrderByIDResponse) GetData() *Order {
	if m != nil {
		return m.Data
	}
	return nil
}

type Order struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId           int64    `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName         string   `protobuf:"bytes,3,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerMobile       string   `protobuf:"bytes,4,opt,name=customer_mobile,json=customerMobile,proto3" json:"customer_mobile,omitempty"`
	DriverId             int64    `protobuf:"varint,5,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DriverName           string   `protobuf:"bytes,6,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	DriverMobile         string   `protobuf:"bytes,7,opt,name=driver_mobile,json=driverMobile,proto3" json:"driver_mobile,omitempty"`
	VehicleId            string   `protobuf:"bytes,8,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	VehicleNo            string   `protobuf:"bytes,9,opt,name=vehicle_no,json=vehicleNo,proto3" json:"vehicle_no,omitempty"`
	PickTime             string   `protobuf:"bytes,10,opt,name=pick_time,json=pickTime,proto3" json:"pick_time,omitempty"`
	PickupLatitude       float64  `protobuf:"fixed64,11,opt,name=pickup_latitude,json=pickupLatitude,proto3" json:"pickup_latitude,omitempty"`
	PickupLongitude      float64  `protobuf:"fixed64,12,opt,name=pickup_longitude,json=pickupLongitude,proto3" json:"pickup_longitude,omitempty"`
	DropoffLatitude      float64  `protobuf:"fixed64,13,opt,name=dropoff_latitude,json=dropoffLatitude,proto3" json:"dropoff_latitude,omitempty"`
	DropoffLongitude     float64  `protobuf:"fixed64,14,opt,name=dropoff_longitude,json=dropoffLongitude,proto3" json:"dropoff_longitude,omitempty"`
	Status               int64    `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            string   `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,17,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35c5e4664fd1dd, []int{6}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Order) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *Order) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *Order) GetCustomerMobile() string {
	if m != nil {
		return m.CustomerMobile
	}
	return ""
}

func (m *Order) GetDriverId() int64 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

func (m *Order) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *Order) GetDriverMobile() string {
	if m != nil {
		return m.DriverMobile
	}
	return ""
}

func (m *Order) GetVehicleId() string {
	if m != nil {
		return m.VehicleId
	}
	return ""
}

func (m *Order) GetVehicleNo() string {
	if m != nil {
		return m.VehicleNo
	}
	return ""
}

func (m *Order) GetPickTime() string {
	if m != nil {
		return m.PickTime
	}
	return ""
}

func (m *Order) GetPickupLatitude() float64 {
	if m != nil {
		return m.PickupLatitude
	}
	return 0
}

func (m *Order) GetPickupLongitude() float64 {
	if m != nil {
		return m.PickupLongitude
	}
	return 0
}

func (m *Order) GetDropoffLatitude() float64 {
	if m != nil {
		return m.DropoffLatitude
	}
	return 0
}

func (m *Order) GetDropoffLongitude() float64 {
	if m != nil {
		return m.DropoffLongitude
	}
	return 0
}

func (m *Order) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Order) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type OrderTrip struct {
	TripId               int64    `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	OrderId              int64    `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId           int64    `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	DriverId             int64    `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	StartTime            string   `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	VacantDistance       float64  `protobuf:"fixed64,7,opt,name=vacant_distance,json=vacantDistance,proto3" json:"vacant_distance,omitempty"`
	EngagedDistance      float64  `protobuf:"fixed64,8,opt,name=engaged_distance,json=engagedDistance,proto3" json:"engaged_distance,omitempty"`
	PickupLatitude       float64  `protobuf:"fixed64,9,opt,name=pickup_latitude,json=pickupLatitude,proto3" json:"pickup_latitude,omitempty"`
	PickupLongitude      float64  `protobuf:"fixed64,10,opt,name=pickup_longitude,json=pickupLongitude,proto3" json:"pickup_longitude,omitempty"`
	DropoffLatitude      float64  `protobuf:"fixed64,11,opt,name=dropoff_latitude,json=dropoffLatitude,proto3" json:"dropoff_latitude,omitempty"`
	DropoffLongitude     float64  `protobuf:"fixed64,12,opt,name=dropoff_longitude,json=dropoffLongitude,proto3" json:"dropoff_longitude,omitempty"`
	Status               int64    `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            string   `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,15,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderTrip) Reset()         { *m = OrderTrip{} }
func (m *OrderTrip) String() string { return proto.CompactTextString(m) }
func (*OrderTrip) ProtoMessage()    {}
func (*OrderTrip) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35c5e4664fd1dd, []int{7}
}

func (m *OrderTrip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderTrip.Unmarshal(m, b)
}
func (m *OrderTrip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderTrip.Marshal(b, m, deterministic)
}
func (m *OrderTrip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderTrip.Merge(m, src)
}
func (m *OrderTrip) XXX_Size() int {
	return xxx_messageInfo_OrderTrip.Size(m)
}
func (m *OrderTrip) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderTrip.DiscardUnknown(m)
}

var xxx_messageInfo_OrderTrip proto.InternalMessageInfo

func (m *OrderTrip) GetTripId() int64 {
	if m != nil {
		return m.TripId
	}
	return 0
}

func (m *OrderTrip) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderTrip) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *OrderTrip) GetDriverId() int64 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

func (m *OrderTrip) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *OrderTrip) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *OrderTrip) GetVacantDistance() float64 {
	if m != nil {
		return m.VacantDistance
	}
	return 0
}

func (m *OrderTrip) GetEngagedDistance() float64 {
	if m != nil {
		return m.EngagedDistance
	}
	return 0
}

func (m *OrderTrip) GetPickupLatitude() float64 {
	if m != nil {
		return m.PickupLatitude
	}
	return 0
}

func (m *OrderTrip) GetPickupLongitude() float64 {
	if m != nil {
		return m.PickupLongitude
	}
	return 0
}

func (m *OrderTrip) GetDropoffLatitude() float64 {
	if m != nil {
		return m.DropoffLatitude
	}
	return 0
}

func (m *OrderTrip) GetDropoffLongitude() float64 {
	if m != nil {
		return m.DropoffLongitude
	}
	return 0
}

func (m *OrderTrip) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OrderTrip) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *OrderTrip) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type OrderDispacherStatus struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId             int64    `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DriverLatitude       float64  `protobuf:"fixed64,3,opt,name=driver_latitude,json=driverLatitude,proto3" json:"driver_latitude,omitempty"`
	DriverLongitude      float64  `protobuf:"fixed64,4,opt,name=driver_longitude,json=driverLongitude,proto3" json:"driver_longitude,omitempty"`
	Status               int64    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDispacherStatus) Reset()         { *m = OrderDispacherStatus{} }
func (m *OrderDispacherStatus) String() string { return proto.CompactTextString(m) }
func (*OrderDispacherStatus) ProtoMessage()    {}
func (*OrderDispacherStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35c5e4664fd1dd, []int{8}
}

func (m *OrderDispacherStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDispacherStatus.Unmarshal(m, b)
}
func (m *OrderDispacherStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDispacherStatus.Marshal(b, m, deterministic)
}
func (m *OrderDispacherStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDispacherStatus.Merge(m, src)
}
func (m *OrderDispacherStatus) XXX_Size() int {
	return xxx_messageInfo_OrderDispacherStatus.Size(m)
}
func (m *OrderDispacherStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDispacherStatus.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDispacherStatus proto.InternalMessageInfo

func (m *OrderDispacherStatus) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderDispacherStatus) GetDriverId() int64 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

func (m *OrderDispacherStatus) GetDriverLatitude() float64 {
	if m != nil {
		return m.DriverLatitude
	}
	return 0
}

func (m *OrderDispacherStatus) GetDriverLongitude() float64 {
	if m != nil {
		return m.DriverLongitude
	}
	return 0
}

func (m *OrderDispacherStatus) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type OrderListResponse struct {
	AllOrder             []*Order `protobuf:"bytes,1,rep,name=all_order,json=allOrder,proto3" json:"all_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderListResponse) Reset()         { *m = OrderListResponse{} }
func (m *OrderListResponse) String() string { return proto.CompactTextString(m) }
func (*OrderListResponse) ProtoMessage()    {}
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35c5e4664fd1dd, []int{9}
}

func (m *OrderListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderListResponse.Unmarshal(m, b)
}
func (m *OrderListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderListResponse.Marshal(b, m, deterministic)
}
func (m *OrderListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderListResponse.Merge(m, src)
}
func (m *OrderListResponse) XXX_Size() int {
	return xxx_messageInfo_OrderListResponse.Size(m)
}
func (m *OrderListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderListResponse proto.InternalMessageInfo

func (m *OrderListResponse) GetAllOrder() []*Order {
	if m != nil {
		return m.AllOrder
	}
	return nil
}

func init() {
	proto.RegisterType((*OrderDispacherStatusRequest)(nil), "pb.OrderDispacherStatusRequest")
	proto.RegisterType((*GeneraResponse)(nil), "pb.GeneraResponse")
	proto.RegisterType((*GetTripByOrderIDRequest)(nil), "pb.GetTripByOrderIDRequest")
	proto.RegisterType((*GetTripByOrderIDResponse)(nil), "pb.GetTripByOrderIDResponse")
	proto.RegisterType((*GetOrderByIDRequest)(nil), "pb.GetOrderByIDRequest")
	proto.RegisterType((*GetOrderByIDResponse)(nil), "pb.GetOrderByIDResponse")
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*OrderTrip)(nil), "pb.OrderTrip")
	proto.RegisterType((*OrderDispacherStatus)(nil), "pb.OrderDispacherStatus")
	proto.RegisterType((*OrderListResponse)(nil), "pb.OrderListResponse")
}

func init() { proto.RegisterFile("pb/orders.proto", fileDescriptor_6d35c5e4664fd1dd) }

var fileDescriptor_6d35c5e4664fd1dd = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x96, 0xdd, 0x4e, 0xd4, 0x40,
	0x14, 0xc7, 0xed, 0x7e, 0xf7, 0xec, 0x27, 0x23, 0x91, 0x02, 0x12, 0xb0, 0x44, 0x85, 0x98, 0x40,
	0x82, 0x31, 0x5e, 0x18, 0x63, 0x44, 0x12, 0xb2, 0x09, 0x60, 0x52, 0xf0, 0x7a, 0x33, 0xdb, 0x19,
	0x96, 0x89, 0xbb, 0x6d, 0x6d, 0x67, 0x37, 0xe1, 0xd2, 0x6b, 0xdf, 0xc8, 0x3b, 0x9f, 0xc0, 0x57,
	0x32, 0x3d, 0x33, 0x9d, 0xfd, 0x2a, 0x88, 0x97, 0xde, 0xcd, 0xfc, 0xcf, 0x9f, 0x73, 0xce, 0x70,
	0x7e, 0x9d, 0x59, 0x68, 0x47, 0xfd, 0xc3, 0x30, 0x66, 0x3c, 0x4e, 0x0e, 0xa2, 0x38, 0x94, 0x21,
	0x29, 0x44, 0xfd, 0x8d, 0x66, 0xd4, 0x3f, 0xec, 0xd3, 0x84, 0x2b, 0xc9, 0xfd, 0x65, 0xc1, 0xe6,
	0xe7, 0xd4, 0x73, 0x22, 0x92, 0x88, 0xfa, 0x37, 0x3c, 0xbe, 0x94, 0x54, 0x8e, 0x13, 0x8f, 0x7f,
	0x1b, 0xf3, 0x44, 0x92, 0x75, 0xa8, 0x61, 0x8a, 0x9e, 0x60, 0x8e, 0xb5, 0x63, 0xed, 0x15, 0xbd,
	0x2a, 0xee, 0xbb, 0x8c, 0x6c, 0x82, 0xcd, 0x62, 0x31, 0x51, 0xb1, 0x02, 0xc6, 0x6a, 0x4a, 0xe8,
	0x32, 0xf2, 0x12, 0xda, 0x3a, 0x38, 0xa4, 0x52, 0xc8, 0x31, 0xe3, 0x4e, 0x71, 0xc7, 0xda, 0xb3,
	0xbc, 0x96, 0x92, 0xcf, 0xb4, 0x4a, 0xf6, 0xa1, 0x93, 0x19, 0xc3, 0x60, 0xa0, 0x9c, 0x25, 0x74,
	0xea, 0x04, 0x67, 0x99, 0x4c, 0x9e, 0x40, 0x25, 0xc1, 0xe6, 0x9c, 0x32, 0x56, 0xd3, 0x3b, 0xd7,
	0x85, 0xd6, 0x29, 0x0f, 0x78, 0x4c, 0x3d, 0x9e, 0x44, 0x61, 0x90, 0x70, 0xd2, 0x81, 0xe2, 0x28,
	0x19, 0x60, 0xc3, 0xb6, 0x97, 0x2e, 0xdd, 0x7d, 0x58, 0x3b, 0xe5, 0xf2, 0x2a, 0x16, 0xd1, 0xf1,
	0x2d, 0x9e, 0xb7, 0x7b, 0x92, 0x1d, 0xb1, 0x05, 0x05, 0x73, 0xb8, 0x82, 0x60, 0xee, 0x7b, 0x70,
	0x96, 0xad, 0x3a, 0xf1, 0x33, 0x28, 0x31, 0x2a, 0x29, 0xba, 0xeb, 0x47, 0xcd, 0x83, 0xa8, 0x7f,
	0x80, 0x96, 0xd4, 0xed, 0x61, 0xc8, 0x7d, 0x0e, 0x8f, 0x4f, 0xb9, 0x44, 0xf5, 0xf8, 0xf6, 0xee,
	0x2a, 0x6f, 0x60, 0x75, 0xde, 0xa6, 0x2b, 0x6c, 0xcd, 0x55, 0xb0, 0x4d, 0x05, 0x9d, 0xfd, 0x77,
	0x09, 0xca, 0xb8, 0xbf, 0x6f, 0x32, 0xdb, 0x50, 0xf7, 0xc7, 0x89, 0x0c, 0x47, 0xb3, 0xb3, 0x81,
	0x4c, 0xea, 0x32, 0xb2, 0x0b, 0x4d, 0x63, 0x08, 0xe8, 0x48, 0xcd, 0xc6, 0xf6, 0x1a, 0x99, 0x78,
	0x41, 0x47, 0x3c, 0x1d, 0xa1, 0x31, 0x8d, 0xc2, 0xbe, 0x18, 0xaa, 0xc1, 0xd8, 0x5e, 0x2b, 0x93,
	0xcf, 0x51, 0x9d, 0x07, 0xa1, 0xbc, 0x00, 0xc2, 0x36, 0xd4, 0x75, 0x10, 0x0b, 0x55, 0x30, 0x03,
	0x28, 0x09, 0xcb, 0xec, 0x42, 0x53, 0x1b, 0x74, 0x91, 0xaa, 0xea, 0x45, 0x89, 0xba, 0xc4, 0x16,
	0xc0, 0x84, 0xdf, 0x08, 0x7f, 0xc8, 0xd3, 0x1a, 0x35, 0x74, 0xd8, 0x5a, 0xe9, 0xb2, 0xd9, 0x70,
	0x10, 0x3a, 0xf6, 0x5c, 0xf8, 0x22, 0x4c, 0x1b, 0x8c, 0x84, 0xff, 0xb5, 0x27, 0xc5, 0x88, 0x3b,
	0x80, 0xd1, 0x5a, 0x2a, 0x5c, 0x09, 0x75, 0xcc, 0x74, 0x3d, 0x8e, 0xa6, 0xa4, 0xd6, 0x15, 0xa9,
	0x4a, 0x9e, 0x25, 0x35, 0x33, 0x1a, 0x52, 0x1b, 0x8a, 0x54, 0xed, 0x34, 0xa4, 0x22, 0xd4, 0x61,
	0x14, 0x5e, 0x5f, 0x4f, 0x93, 0x36, 0x33, 0xa8, 0x51, 0x37, 0x59, 0x5f, 0xc1, 0x8a, 0xb1, 0x9a,
	0xb4, 0x2d, 0xf4, 0x66, 0x39, 0xf2, 0xbe, 0x80, 0xf6, 0xec, 0x17, 0x40, 0x9e, 0x82, 0xed, 0xc7,
	0x9c, 0x4a, 0xce, 0x3e, 0x4a, 0xa7, 0xa3, 0x8e, 0x6f, 0x84, 0x34, 0x3a, 0x8e, 0x98, 0x8e, 0xae,
	0xa8, 0xa8, 0x11, 0xdc, 0x1f, 0x25, 0xb0, 0x0d, 0xc3, 0x64, 0x0d, 0xaa, 0x32, 0x16, 0xd1, 0x14,
	0xaa, 0x4a, 0xba, 0xed, 0xb2, 0x39, 0xdc, 0x0a, 0xf7, 0xe2, 0x56, 0x5c, 0xc2, 0x6d, 0x0e, 0x90,
	0xd2, 0x02, 0x20, 0x5b, 0x00, 0x89, 0xa4, 0xb1, 0x54, 0xd3, 0x29, 0xab, 0xf6, 0x50, 0xc1, 0xf1,
	0xac, 0x43, 0x8d, 0x07, 0x4c, 0x05, 0x15, 0x3c, 0x55, 0x1e, 0xb0, 0x6c, 0x72, 0x13, 0xea, 0xd3,
	0x40, 0xf6, 0x98, 0x48, 0x24, 0x0d, 0x7c, 0xc5, 0x8e, 0xe5, 0xb5, 0x94, 0x7c, 0xa2, 0xd5, 0x74,
	0x1c, 0x3c, 0x18, 0xd0, 0x01, 0x67, 0x53, 0x67, 0x4d, 0x8d, 0x43, 0xeb, 0xc6, 0x9a, 0x43, 0x83,
	0xfd, 0x60, 0x1a, 0xe0, 0xe1, 0x34, 0xd4, 0xff, 0x81, 0x86, 0xc6, 0x5f, 0x69, 0x68, 0xde, 0x4d,
	0x43, 0xeb, 0x5e, 0x1a, 0xda, 0x8b, 0x34, 0xfc, 0xb4, 0x60, 0x35, 0xef, 0x3d, 0xf8, 0x2f, 0x1e,
	0x82, 0x77, 0xb0, 0x82, 0xbd, 0x9f, 0x89, 0x44, 0x9a, 0x0b, 0xf5, 0x05, 0xd8, 0x74, 0x38, 0xec,
	0x61, 0xb3, 0x8e, 0xb5, 0x53, 0x9c, 0xbf, 0x55, 0x6b, 0x74, 0x38, 0xc4, 0xd5, 0xd1, 0xf7, 0x02,
	0x34, 0x70, 0x75, 0xc9, 0xe3, 0x89, 0xf0, 0x39, 0x79, 0x0b, 0x8d, 0xd9, 0x1b, 0x9a, 0xac, 0xa5,
	0x7f, 0x95, 0x73, 0xb5, 0x6f, 0x34, 0xd2, 0x40, 0x56, 0xcf, 0x7d, 0x44, 0xf6, 0xa0, 0xfe, 0x09,
	0xff, 0xdd, 0xea, 0xa2, 0x9e, 0x56, 0x5b, 0x72, 0x7e, 0x80, 0xce, 0xe2, 0x53, 0x43, 0x36, 0x75,
	0x99, 0xbc, 0xb7, 0x6a, 0x29, 0xc1, 0x39, 0x6c, 0x7c, 0xc1, 0xd9, 0xe5, 0xce, 0x6c, 0xdb, 0x54,
	0xce, 0x7f, 0xdd, 0x17, 0xd3, 0xf5, 0x2b, 0xf8, 0xa3, 0xe0, 0xf5, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xdb, 0x9b, 0xa0, 0x0e, 0x3a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	GetOrderByID(ctx context.Context, in *GetOrderByIDRequest, opts ...grpc.CallOption) (*Response, error)
	CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Response, error)
	GetTripByOrderID(ctx context.Context, in *GetTripByOrderIDRequest, opts ...grpc.CallOption) (*Response, error)
	UpdateOrderDispacherStatus(ctx context.Context, in *OrderDispacherStatusRequest, opts ...grpc.CallOption) (*Response, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) GetOrderByID(ctx context.Context, in *GetOrderByIDRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.OrderService/GetOrderByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetTripByOrderID(ctx context.Context, in *GetTripByOrderIDRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.OrderService/GetTripByOrderID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateOrderDispacherStatus(ctx context.Context, in *OrderDispacherStatusRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.OrderService/UpdateOrderDispacherStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	GetOrderByID(context.Context, *GetOrderByIDRequest) (*Response, error)
	CreateOrder(context.Context, *Order) (*Response, error)
	GetTripByOrderID(context.Context, *GetTripByOrderIDRequest) (*Response, error)
	UpdateOrderDispacherStatus(context.Context, *OrderDispacherStatusRequest) (*Response, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) GetOrderByID(ctx context.Context, req *GetOrderByIDRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderByID not implemented")
}
func (*UnimplementedOrderServiceServer) CreateOrder(ctx context.Context, req *Order) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedOrderServiceServer) GetTripByOrderID(ctx context.Context, req *GetTripByOrderIDRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTripByOrderID not implemented")
}
func (*UnimplementedOrderServiceServer) UpdateOrderDispacherStatus(ctx context.Context, req *OrderDispacherStatusRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderDispacherStatus not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_GetOrderByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/GetOrderByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderByID(ctx, req.(*GetOrderByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetTripByOrderID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripByOrderIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetTripByOrderID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/GetTripByOrderID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetTripByOrderID(ctx, req.(*GetTripByOrderIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateOrderDispacherStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderDispacherStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateOrderDispacherStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/UpdateOrderDispacherStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateOrderDispacherStatus(ctx, req.(*OrderDispacherStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderByID",
			Handler:    _OrderService_GetOrderByID_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "GetTripByOrderID",
			Handler:    _OrderService_GetTripByOrderID_Handler,
		},
		{
			MethodName: "UpdateOrderDispacherStatus",
			Handler:    _OrderService_UpdateOrderDispacherStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/orders.proto",
}
